name: camera_permission_handling
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  photo_manager: ^3.2.1
  camera: ^0.10.5+9
  image_picker: ^1.0.8
  flutter_sound: ^9.2.13
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
